name: Enable automerge on release PRs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  wait-for-stability:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

  auto-merge-release:
    needs: wait-for-stability
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release-please-')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.CI }}

      - name: Enable automerge on release PR
        run: gh pr merge --squash --auto ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.CI }}
