name: Enable automerge on release PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge-release:
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'autorelease')
    steps:
      - name: Enable automerge on release PR
        run: gh pr merge --squash --auto "1"
        env:
          GH_TOKEN: ${{ secrets.CI }}
