name: Enable automerge on release PRs

on:
  pull_request_target:
  push:
    branches:
      - "release-please-*"

jobs:
  auto-merge-release:
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'autorelease:pending')
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.CI }}
          allowed-author: "github-actions[bot]"
          merge-method: SQUASH
