name: Enable automerge on release PRs

on:
  pull_request_target:

jobs:
  auto-merge-release:
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.CI }}
          allowed-author: "github-actions[bot]"
          merge-method: SQUASH
