name: Enable automerge on release PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  wait-for-stability:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

  auto-merge-release:
    needs: wait-for-stability
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, vars.RELEASE_LABEL)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Enable automerge on release PR
        run: gh pr merge --squash --auto ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.CI }}
