name: Enable automerge on release PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge-release:
    name: Enable automerge on release PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Enable automerge on release PR
        run: gh pr merge --squash --auto "{{ github.event.number }}"
        env:
          GH_TOKEN: ${{ secrets.CI }}
